### ISSUE TITLE
Future: 希望为ws链接下发初始化信息

### ISSUE THREAD

**Issue by LittleJiu-furry** [AynaLivePlayer/AynaLivePlayer#10]
## 为什么需要
我分析了0.9.11版本时的的ws，发现前端页面会在连接ws之前向`/api/info`接口发送请求以获得当前的一些信息，但是当只留下纯ws时这一部分无法实现，只能等待ws事件下发

## 需要怎么实现
希望在ws客户端连接到播放器的ws服务器时，由服务器主动下发或者客户端向服务器发送一个hello消息后由服务器下发当前数据

##  是否已现有此功能
我分析了dev分支的代码，`/api/info`接口依旧存在，因此认为可以在ws部分复用这一接口中获得当前数据的逻辑

**Comment by aynakeya** [comment]
dev分支已更新，目前会在建立websocket的时候下发每一个eventId最新的数据。

理论上应该能够解决你的问题。
